export const FALLBACK_UNIVERSITY_SOURCES = [
  {
    key: "ucl",
    name: "University College London",
    aliases: ["ucl", "university college london"],
    country: "United Kingdom",
    city: "London",
    website: "https://www.ucl.ac.uk",
    admissionsUrl: "https://www.ucl.ac.uk/prospective-students/undergraduate",
    defaultProgram: "BSc Computer Science",
    level: "undergraduate",
    platform: "UCAS",
    platformConfidenceLevel: "PlatformDefault",
    courseUrl: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/computer-science-bsc",
    confidenceLevel: "NeedsVerification",
    sourceName: "Demo fallback source",
    sourceUrl: "https://www.ucl.ac.uk/prospective-students/undergraduate",
    notes: "Fallback record. Course-level details must be refreshed before submission. No UCL-specific essay is generated without source data.",
  },
  {
    key: "kcl",
    name: "King's College London",
    aliases: ["kcl", "king's college london", "kings college london"],
    country: "United Kingdom",
    city: "London",
    website: "https://www.kcl.ac.uk",
    admissionsUrl: "https://www.kcl.ac.uk/study/undergraduate",
    defaultProgram: "BSc Computer Science",
    level: "undergraduate",
    platform: "UCAS",
    platformConfidenceLevel: "PlatformDefault",
    courseUrl: "https://www.kcl.ac.uk/study/undergraduate",
    confidenceLevel: "NeedsVerification",
    sourceName: "Demo fallback source",
    sourceUrl: "https://www.kcl.ac.uk/study/undergraduate",
    notes: "Fallback UCAS choice. Supplemental essays are not generated unless source data confirms them.",
  },
  {
    key: "edinburgh",
    name: "University of Edinburgh",
    aliases: ["edinburgh", "university of edinburgh"],
    country: "United Kingdom",
    city: "Edinburgh",
    website: "https://www.ed.ac.uk",
    admissionsUrl: "https://www.ed.ac.uk/studying/undergraduate",
    defaultProgram: "BSc Computer Science",
    level: "undergraduate",
    platform: "UCAS",
    platformConfidenceLevel: "PlatformDefault",
    confidenceLevel: "NeedsVerification",
    sourceName: "Demo fallback source",
    sourceUrl: "https://www.ed.ac.uk/studying/undergraduate",
    notes: "Fallback UCAS choice with university-specific verification tasks only.",
  },
  {
    key: "manchester",
    name: "University of Manchester",
    aliases: ["manchester", "university of manchester"],
    country: "United Kingdom",
    city: "Manchester",
    website: "https://www.manchester.ac.uk",
    admissionsUrl: "https://www.manchester.ac.uk/study/undergraduate/",
    defaultProgram: "BSc Computer Science",
    level: "undergraduate",
    platform: "UCAS",
    platformConfidenceLevel: "PlatformDefault",
    confidenceLevel: "NeedsVerification",
    sourceName: "Demo fallback source",
    sourceUrl: "https://www.manchester.ac.uk/study/undergraduate/",
    notes: "Fallback UCAS choice with university-specific verification tasks only.",
  },
  {
    key: "nyuad",
    name: "NYU Abu Dhabi",
    aliases: ["nyu abu dhabi", "nyuad", "new york university abu dhabi"],
    country: "UAE",
    city: "Abu Dhabi",
    website: "https://nyuad.nyu.edu",
    admissionsUrl: "https://nyuad.nyu.edu/en/admissions.html",
    defaultProgram: "Computer Science BA",
    level: "undergraduate",
    platform: "DirectPortal",
    platformConfidenceLevel: "NeedsVerification",
    confidenceLevel: "NeedsVerification",
    sourceName: "Demo fallback source",
    sourceUrl: "https://nyuad.nyu.edu/en/admissions.html",
    notes: "Fallback non-UCAS application. Essay requirements remain Needs verification.",
    directEssays: [
      {
        title: "NYUAD direct portal statement",
        essayType: "DirectPortalStatement",
        prompt: "Confirm the current NYUAD writing requirement in the official portal before drafting.",
        wordLimit: 400,
        confidenceLevel: "NeedsVerification",
      },
    ],
  },
  {
    key: "toronto",
    name: "University of Toronto",
    aliases: ["university of toronto", "toronto", "uoft", "u of t"],
    country: "Canada",
    city: "Toronto",
    website: "https://www.utoronto.ca",
    admissionsUrl: "https://future.utoronto.ca/apply/",
    defaultProgram: "Computer Science, Faculty of Arts & Science",
    level: "undergraduate",
    platform: "OUAC",
    platformConfidenceLevel: "NeedsVerification",
    confidenceLevel: "NeedsVerification",
    sourceName: "Demo fallback source",
    sourceUrl: "https://future.utoronto.ca/apply/",
    notes: "Fallback OUAC/platform application. Verify program and document rules.",
  },
];
